@CP.Portal.Api_HostAddress = http://localhost:5256

GET {{CP.Portal.Api_HostAddress}}/api/movies
Accept: application/json

###

#Create Movie
POST {{CP.Portal.Api_HostAddress}}/api/movies
Content-Type: application/json
Accept: Application/json

{
"title": "33pp",
"releaseYear": "2025-01-01",
"durationMinutes": 120,
"language": "en",
"price": 9.99,
"originalTitle": "Avatar X Air",
"description": "test"
}

###

#Update movie rent price
PUT {{CP.Portal.Api_HostAddress}}/api/movies/019d3683-129c-780c-bd1a-7ef5a2689dcb/price
Content-Type: application/json
Accept: Application/json

{
    "newPrice": "1000"
}

###

#Delete Movie
DELETE {{CP.Portal.Api_HostAddress}}/api/movies/019d3eff-9776-713d-8289-c389f7d11587
Content-Type: application/json
Accept: Application/json

###

#Get Movie Details
GET {{CP.Portal.Api_HostAddress}}/api/movies/019d6605-0966-7624-9d5b-88e946770a25
Content-Type: application/json
Accept: Application/json

###

# @name Login
POST {{CP.Portal.Api_HostAddress}}/api/users/login
Content-Type: application/json
Accept: Application/json

{
"email": "jodiaz@mail.com",
"password": "NetUniversity@90"
}

###

@bearerToken = {{Login.response.body.$.token}}

# @name cartItem
POST {{CP.Portal.Api_HostAddress}}/api/cart
Content-Type: application/json
Accept: Application/json
Authorization: Bearer {{bearerToken}}

{
"movieId": "019d6605-0966-7624-9d5b-88e946770a25",
"quantity": 2
}

###

#Get User Details
GET {{CP.Portal.Api_HostAddress}}/api/users/me
Content-Type: application/json
Accept: Application/json
Authorization: Bearer {{bearerToken}}

###

# @name RegisterUser
POST {{CP.Portal.Api_HostAddress}}/api/users
Content-Type: application/json
Accept: Application/json

{
"email": "carlo@mail.com",
"password": "NetUniversity@90"
}

###