@CP.Portal.Api_HostAddress = http://localhost:5256

GET {{CP.Portal.Api_HostAddress}}/api/movies
Accept: application/json

###

#Create Movie
POST {{CP.Portal.Api_HostAddress}}/api/movies
Content-Type: application/json
Accept: Application/json

{
"title": "",
"releaseYear": "2025-01-01",
"durationMinutes": 120,
"language": "en",
"price": 9.99,
"originalTitle": "Avatar X Air",
"description": "test"
}

###

#Update movie rent price
PUT {{CP.Portal.Api_HostAddress}}/api/movies/019d3683-129c-780c-bd1a-7ef5a2689dcb/price
Content-Type: application/json
Accept: Application/json

{
    "newPrice": "1000"
}

###
