// <auto-generated />
using System;
using CP.Portal.Movies.Module.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CP.Portal.Movies.Module.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20260327214912_InitialMovies")]
    partial class InitialMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("movies")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("GenreId")
                        .HasName("pk_genres");

                    b.ToTable("genres", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Movie", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("original_title");

                    b.Property<DateOnly>("ReleaseYear")
                        .HasColumnType("date")
                        .HasColumnName("release_year");

                    b.Property<decimal>("RentalPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rental_price");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("MovieId")
                        .HasName("pk_movies");

                    b.ToTable("movies", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieCast", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("CastOrder")
                        .HasColumnType("integer")
                        .HasColumnName("cast_order");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("character_name");

                    b.HasKey("MovieId", "PersonId")
                        .HasName("pk_movie_casts");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movie_casts_person_id");

                    b.ToTable("movie_casts", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieCrew", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("MovieId", "PersonId")
                        .HasName("pk_movies_crews");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_movies_crews_person_id");

                    b.ToTable("movies_crews", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieGenre", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.HasKey("MovieId", "GenreId")
                        .HasName("pk_movie_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_movie_genres_genre_id");

                    b.HasIndex("MovieId")
                        .HasDatabaseName("ix_movie_genres_movie_id");

                    b.ToTable("movie_genres", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("PersonId")
                        .HasName("pk_persons");

                    b.ToTable("persons", "movies");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieCast", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Movie", "Movie")
                        .WithMany("Casts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_casts_movies_movie_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Person", "Person")
                        .WithMany("Casts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_casts_persons_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieCrew", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Movie", "Movie")
                        .WithMany("Crewers")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_crews_movies_movie_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Person", "Person")
                        .WithMany("Crewers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movies_crews_peoples_person_id");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.MovieGenre", b =>
                {
                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_genres_genre_id");

                    b.HasOne("CP.Portal.Movies.Module.Data.Damain.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movie_genres_movies_movie_id");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Movie", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Crewers");

                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CP.Portal.Movies.Module.Data.Damain.Person", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Crewers");
                });
#pragma warning restore 612, 618
        }
    }
}
